#!/bin/sh
# dmpc, an mpc wrapper using dmenu

options="\
play/pause (toggle)\
\nnext song\
\nprevious song\
\nchange song\
\nstop\
\nupdate database\
\nrefill queue\
\nrepeat\
\nrandom\
\nsingle\
\nconsume\
\nexit\
\n\
\n\
"

while true; do
	i_hate_sh="$(mpc | grep -v '\[.*\]')" # GNU/God, why can't double and single quotes be the same?
	# shellcheck disable=SC2059
	case $(echo "$options$i_hate_sh" | dmenu -i -p dmpc) in
		"play/pause (toggle)")
			mpc toggle
			;;
		"next song")
			mpc next
			;;
		"previous song")
			mpc prev
			;;
		"change song")
			mpc playlist | nl -s ' ' | dmenu -i -p "select song" | awk '{print $1}' | xargs -I {} mpc play "{}"
			;;
		"stop")
			mpc stop
			;;
		"update database")
			mpc update
			;;
		"refill queue")
			mpc clear && mpc ls | mpc add
			;;
		"repeat")
			mpc repeat
			;;
		"random")
			mpc random
			;;
		"single")
			mpc single
			;;
		"consume")
			mpc consume
			;;
		*)
			break
			;;
	esac
done
